---
# file: rpiservers.yml

- hosts: rpiservers
  name: Bootstrap Raspberry Pi servers
  become: yes
  roles:
    - role: common/ip
    - role: cluster/download
      tags: download
    - role: cluster/prereq
      tags: prereq

- hosts: initial_controller
  name: Bootstrap initial controller
  gather_facts: yes
  become: yes
  roles:
    - role: cluster/k0s/initial_controller
      tags: init

- hosts: controller
  name: Configure k0s control plane nodes
  gather_facts: yes
  become: yes
  serial: 1
  roles:
    - role: cluster/k0s/controller
      tags: server

- hosts: worker
  name: Configure k0s worker nodes
  become: yes
  roles:
    - role: cluster/k0s/worker
      tags: worker
