---
- name: Create k0s initial controller service with install command
  register: install_initial_controller_cmd
  command: k0s install controller -c {{ k0s_config_dir }}/k0s.yaml --single {{ extra_args | default(omit) }}
  changed_when: install_initial_controller_cmd | length > 0

- name: Setup custom environment variables for systemd unit
  include_role:
    name: k0s/common/env_setup

- name: Enable and check k0s service
  systemd:
    name: k0scontroller
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Wait for k8s apiserver
  wait_for:
    host: localhost
    port: 6443
    delay: 15
    timeout: 180

- name: Copy config file to user home directory
  copy:
    src: "{{ k0s_data_dir }}/pki/admin.conf"
    dest: ~{{ ansible_user }}/k0s-kubeconfig.yml
    remote_src: yes
    owner: "{{ ansible_user }}"
    mode: 0644

- name: Set controller IP in kubeconfig
  replace:
    path: ~{{ ansible_user }}/k0s-kubeconfig.yml
    regexp: "localhost"
    replace: "{{ ansible_default_ipv4.address }}"

- name: Copy kubeconfig
  become: false
  fetch:
    src: "~{{ ansible_user }}/k0s-kubeconfig.yml"
    dest: "{{ artifacts_dir }}/k0s-kubeconfig-single.yml"
    flat: yes
    validate_checksum: no

- name: "print kubeconfig command"
  debug:
    msg: "To use Cluster: copy the content in {{ artifacts_dir }}/k0s-kubeconfig-single.yml to your kubeconfig file."
