---
- name: Install "unattended_upgrades" package
  include_role:
    name: utils/install_package
  vars:
    packages:
      - unattended-upgrades
      - apt-listchanges


- name: Create periodic updates with the "02periodic" file
  copy:
    src: "{{ role_path }}/files/02periodic"
    dest: "{{ unattended_upgrades_path }}"
    owner: root
    group: root
    mode: 0644
    force: yes
