---
- name: Install "ufw" package
  include_role:
    name: utils/install_package
  vars:
    packages:
      - ufw

- name: Set logging
  ufw:
    logging: "on"

- name: Deny incoming traffic on all ports
  ufw:
    default: deny
    direction: incoming

- name: Allow outgoing traffic on all ports
  ufw:
    default: allow
    direction: outgoing

- name: Allow certain tcp connections
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - "80"
    - "443"
    - "9443"
    - "6443"
    - 2379:2380
    - "10250"
    - 30000:32767

- name: Limit SSH connections
  ufw:
    rule: limit
    port: "{{ ansible_ssh_port | mandatory | quote }}"
    proto: tcp
  notify: enable ufw
