---
- name: Ensure Network "interface" is configured
  lineinfile:
    path: "{{ dhcpcd_config_path }}"
    regex: "^interface {{ ansible_default_ipv4.interface }}"
    insertafter: "^#interface {{ ansible_default_ipv4.interface }}"
    line: "interface {{ ansible_default_ipv4.interface }}"
    group: netdev
    owner: root
    mode: 0664
    create: yes
  register: interface_configured

- name: Ensure Network "static ip_address" is configured
  lineinfile:
    path: "{{ dhcpcd_config_path }}"
    regex: "^static ip_address="
    insertafter: "^#static ip_address="
    line: "static ip_address={{ ansible_default_ipv4.address }}"
    group: netdev
    owner: root
    mode: 0664
    create: yes
  register: static_ip_address_configured

- name: Ensure Network "static routers" is configured
  lineinfile:
    path: "{{ dhcpcd_config_path }}"
    regex: "^static routers="
    insertafter: "^#static routers="
    line: "static routers={{ ansible_default_ipv4.gateway }}"
    group: netdev
    owner: root
    mode: 0664
    create: yes
  register: static_routers_configured

- name: Ensure Network "static domain_name_servers" is configured
  lineinfile:
    path: "{{ dhcpcd_config_path }}"
    regex: "^static domain_name_servers="
    insertafter: "^#static domain_name_servers="
    line: "static domain_name_servers={{ ansible_default_ipv4.gateway }}"
    group: netdev
    owner: root
    mode: 0664
    create: yes
  register: static_domain_name_servers_configured

- name: Reboot host
  reboot:
    connect_timeout: "{{ reboot_connect_timeout }}"
    msg: "Reboot initiated for static IP configuration"
    post_reboot_delay: "{{ reboot_post_reboot_delay }}"
    pre_reboot_delay: "{{ reboot_pre_reboot_delay }}"
    reboot_timeout: "{{ reboot_timeout }}"
    test_command: "{{ reboot_test_command }}"
  when:
    - interface_configured.changed
    - static_ip_address_configured.changed
    - static_routers_configured.changed
    - static_domain_name_servers_configured.changed
