---
# file: roles/cluster/download/tasks/amd.yml

- name: Download k0s binary k0s-{{ k0s_version }}-amd64
  get_url:
    url: https://github.com/k0sproject/k0s/releases/download/{{ k0s_version }}/k0s-{{ k0s_version }}-amd64
    dest: "{{ k0s_binary_dest }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
