---
# file: roles/cluster/download/tasks/arm.yml

- name: Download k0s binary k0s-{{ k0s_version }}-arm64
  get_url:
    url: https://github.com/k0sproject/k0s/releases/download/{{ k0s_version }}/k0s-{{ k0s_version }}-arm64
    dest: "{{ k0s_binary_dest }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
