---
# file: roles/firewall/enable/tasks/main.yml

- name: Enable "ufw" service
  service:
    name: ufw
    enabled: yes

- name: Start "ufw" service
  service:
    name: ufw
    state: started

- name: Restart "ufw" service
  service:
    name: ufw
    state: restarted
