---
- name: Install package
  include_role:
    - utils/install_package
  vars:
    packages:
      - fail2ban

- name: Create custom configuration file for 'Fail2ban'
  copy:
    src: "{{ role_path }}/files/fail2ban.conf"
    dest: "{{ fail2ban_conf_path }}"
    force: yes

- name: Create custom configuration files for 'Jail Fail2ban'
  copy:
    src: "{{ role_path }}/files/jail.conf"
    dest: "{{ jail_conf_path }}"
    force: yes

- name: Enable "fail2ban" service
  notify: restart fail2ban
