---
- name: Ensure disable Root SSH login
  lineinfile:
    path: "{{ sshd_config_path }}"
    regex: "^PermitRootLogin "
    insertafter: "^#PermitRootLogin "
    line: "#PermitRootLogin prohibit-password"
    group: root
    owner: root
    mode: 0644
    create: yes

- name: Ensure use SSH keys instead of passwords
  lineinfile:
    path: "{{ sshd_config_path }}"
    regex: "^PasswordAuthentication "
    insertafter: "^#PasswordAuthentication "
    line: "PasswordAuthentication no"
    group: root
    owner: root
    mode: 0644
    create: yes

- name: Ensure SSH port is set to {{ ssh_port }}
  lineinfile:
    path: "{{ sshd_config_path }}"
    regex: "^Port "
    insertafter: "^#Port "
    line: "Port {{ ssh_port }}"
    group: root
    owner: root
    mode: 0644
    create: yes

- name: Restart SSH service
  service:
    name: ssh
    state: restarted

- name: Change ansible ssh port variable to {{ ssh_port }}
  set_fact:
    ansible_port: "{{ ssh_port }}"
