---
- name: Install "cgroup-lite", "cgroup-tools" and "cgroupfs-mount" on RHEL Family OS
  include_tasks: rhel.yml
  when: ansible_os_family == "RedHat"

- name: Install "cgroup-lite", "cgroup-tools" and "cgroupfs-mount" on Debian Family OS
  include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Configure "CGroup"
  lineinfile:
    path: "{{ cmdline_path }}"
    regex: "^cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1"
    insertafter: "^#cgroup_enable=cpuset #cgroup_enable=memory #cgroup_memory=1"
    line: "cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1"
    group: root
    owner: root
    mode: 0664
    create: yes
  register: configuration

- name: Reboot host
  reboot:
    connect_timeout: "{{ reboot_connect_timeout }}"
    msg: "Reboot initiated for static IP configuration"
    post_reboot_delay: "{{ reboot_post_reboot_delay }}"
    pre_reboot_delay: "{{ reboot_pre_reboot_delay }}"
    reboot_timeout: "{{ reboot_timeout }}"
    test_command: "{{ reboot_test_command }}"
  when: configuration.changed
